
spring:
  application:
    name: service-registro
  data:
    mongodb:
      host: localhost
      port: 27017
      database: registro
  mail:
    host: smtp.gmail.com
    port: 465
    username: torneoesport2@gmail.com
    password: Planta123
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

server:
  port: 8082