
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: registro
  mail:
    host: smtp.gmail.com
    port: 465
    username: torneoesport2@gmail.com
    password: Planta123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            enable: true
          

server:
  port: 8082